before_install:
- wget http://www.deflaker.org/maven/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
language: java
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
dist: trusty
sudo: required
jdk: openjdk8
matrix:
  include:
    - dist: precise
      jdk: openjdk6
    - #dist: trusty
      jdk: openjdk7
    - #dist: trusty
      jdk: openjdk8
env:
  matrix:
    - JACKSON_VERSION=2.6.0
    - JACKSON_VERSION=2.5.0
    - JACKSON_VERSION=2.4.0
    - JACKSON_VERSION=2.3.0
script:
  - mvn clean install -Djackson.version=$JACKSON_VERSION
